abstract final class RouteNames {
  static const splash = 'splash';
  static const login = 'login';
  static const register = 'register';
  static const forgotPassword = 'forgot-password';
  static const onboarding = 'onboarding';
  static const home = 'home';
  static const quiz = 'quiz';
  static const quizAttempt = 'quiz-attempt';
  static const quizResult = 'quiz-result';
  static const calculator = 'calculator';
  static const calculators = 'calculators';
  static const courses = 'courses';
  static const battle = 'battle';
  static const profile = 'profile';
  static const settings = 'settings';
  static const achievements = 'achievements';
  static const library = 'library';
  static const libraryDetail = 'library-detail';
  static const tutorChat = 'tutor-chat';
  static const tutorPlan = 'tutor-plan';
  static const tutorOnboarding = 'tutor-onboarding';
  static const coaching = 'coaching';
  static const coachingDashboard = 'coaching-dashboard';
  // Economy — wallet/ledger/shop/inventory (WO-1/WO-2 beta, inventory live)
  static const economy = 'economy';
  static const economyWallet = 'economy-wallet';
  static const economyShop = 'economy-shop';
  static const economyInventory = 'economy-inventory';
  // Store — premium assets / wardrobe / market (WO-3 beta)
  static const store = 'store';
  static const premiumStore = 'premium-store';
  static const wardrobe = 'wardrobe';
  static const market = 'market';
  // Streak + Leaderboard + Contests + Live Events — Part 4 (WO-4)
  static const streak = 'streak';
  static const leaderboard = 'leaderboard';
  static const contests = 'contests';
  static const contestDetail = 'contest-detail';
  static const liveEvents = 'live-events';
  static const liveEventDetail = 'live-event-detail';
  // Learning — Part 4
  static const learning = 'learning';
  static const learningTracks = 'learning-tracks';
  static const learningToday = 'learning-today';
  static const learningGoalDetail = 'learning-goal-detail';
  static const learningReviews = 'learning-reviews';
  // Practice — Part 4
  static const practice = 'practice';
  static const practiceSession = 'practice-session';
}
