abstract final class RouteNames {
  static const splash = 'splash';
  static const login = 'login';
  static const register = 'register';
  static const forgotPassword = 'forgot-password';
  static const onboarding = 'onboarding';
  static const home = 'home';
  static const quiz = 'quiz';
  static const quizAttempt = 'quiz-attempt';
  static const quizResult = 'quiz-result';
  static const calculator = 'calculator';
  static const calculators = 'calculators';
  static const courses = 'courses';
  static const battle = 'battle';
  static const profile = 'profile';
  static const settings = 'settings';
  static const achievements = 'achievements';
  static const library = 'library';
  static const libraryDetail = 'library-detail';
  static const tutorChat = 'tutor-chat';
  static const tutorPlan = 'tutor-plan';
  static const tutorOnboarding = 'tutor-onboarding';
  static const coaching = 'coaching';
  static const coachingDashboard = 'coaching-dashboard';
}
